apiVersion: apps/v1
kind: Deployment
metadata:
  name: otus-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otus-profile
  template:
    metadata:
      labels:
        app: otus-profile
    spec:
      containers:
        - name: otus-profile
          image: mazurenkoaa/otus-auth
          ports:
            - containerPort: 8000
          command: ['uvicorn', 'src.profile:app', '--host', '0.0.0.0', '--port', '8000']
